{
 "title": "Mail",
 "tags": [
  "is-services",
  "charm: postfix-relay"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "prometheusds", "label": "Prometheus datasource", "query": "prometheus" },
   {
    "name": "juju_unit",
    "label": "Juju unit",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_application=~\"$juju_application\"},juju_unit)"
    }
   },
   {
    "name": "juju_application",
    "label": "Juju application",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\"},juju_application)"
    }
   },
   {
    "name": "juju_model_uuid",
    "label": "Juju model uuid",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\"},juju_model_uuid)"
    }
   },
   {
    "name": "juju_model",
    "label": "Juju Model",
    "query": {
     "query": "label_values(postfix_queue_length{}, juju_model)"
    }
   },
   {
    "name": "juju_smtp_relay_unit",
    "label": "SMTP Unit",
    "query": {
     "query": "label_values(postfix_queue_length{host=~\"^$juju_model.*\"}, host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "SMTP Relay", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Mail Queue Length (msgs)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(juju_model, juju_unit, queue, host) (postfix_queue_length{host=~\"$juju_smtp_relay_unit\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"})",
     "legendFormat": " {{host}} {{queue}}"
    }
   ]
  },
  {
   "title": "SMTP Processes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(juju_model, juju_unit, host) (procstat_lookup_running{exe=\"smtpd\",host=~\"$juju_smtp_relay_unit\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"})",
     "legendFormat": "{{host}} {{queue}} smtpd"
    },
    {
     "expr": "sum by(juju_model, juju_unit, host) (procstat_lookup_running{exe=\"smtp\",host=~\"$juju_smtp_relay_unit\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}) - sum by(juju_model, juju_unit, host) (procstat_lookup_running{exe=\"smtpd\",host=~\"$juju_smtp_relay_unit\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"})",
     "legendFormat": "{{host}} {{queue}} smtp"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "cpu_usage_user{cpu=\"cpu-total\",host=~\"$juju_smtp_relay_unit\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "{{host}} user"
    },
    {
     "expr": "cpu_usage_system{cpu=\"cpu-total\",host=~\"$juju_smtp_relay_unit\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "{{host}} system"
    },
    {
     "expr": "cpu_usage_iowait{cpu=\"cpu-total\",host=~\"$juju_smtp_relay_unit\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "{{host}} iowait"
    }
   ]
  },
  {
   "title": "TCP Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "netstat_tcp_established{host=~\"$juju_smtp_relay_unit\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"}",
     "legendFormat": "{{host}} Established"
    }
   ]
  },
  {
   "title": "Mail Queue Age (age of oldest item in seconds)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 6, "y": 17 },
   "targets": [
    {
     "expr": "sum by(juju_model, juju_unit, queue, host) (postfix_queue_age{host=~\"$juju_smtp_relay_unit\",juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"})",
     "legendFormat": " {{host}} {{queue}}"
    }
   ]
  }
 ]
}